// Port of linuxdoom-1.10 d_main.c -- DOOM main program (D_DoomMain) and game
// loop (D_DoomLoop), plus functions to determine game mode (shareware,
// registered), parse command line parameters, configure game parameters
// (turbo), and call the startup functions.
//
// Host-driven restructure: the never-returning D_DoomLoop becomes
// D_DoomStep(), called by the host once per display frame, and D_Display's
// blocking wipe do/while becomes a wipeActive state machine (D_WipeStep).
// WAD files arrive as in-memory ByteArrays instead of file paths, so
// IdentifyVersion becomes D_IdentifyVersion (by lump presence, after
// W_InitMultipleFiles).
// Original code (C) 1993-1996 id Software, Inc., released under the GNU GPL v2.
@file:Suppress("FunctionName", "ClassName", "PropertyName", "LocalVariableName",
    "unused", "UNUSED_PARAMETER", "UNUSED_VARIABLE", "MagicNumber", "ktlint")

package doom.engine

// doomdef.h: DOOM version
const val VERSION = 110

var devparm = false      // started game with -devparm
var nomonsters = false   // checkparm of -nomonsters
var respawnparm = false  // checkparm of -respawn
var fastparm = false     // checkparm of -fast

var singletics = false   // debug flag to cancel adaptiveness

// Set if homebrew PWAD stuff has been added. (C: defined in g_game.c,
// assigned per-unit to d_main in this port.)
var modifiedgame = false

var startskill = sk_medium
var startepisode = 1
var startmap = 1
var autostart = false

var advancedemo = false

//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
const val MAXEVENTS = 64  // d_event.h

val events = Array(MAXEVENTS) { event_t() }
var eventhead = 0
var eventtail = 0

//
// D_PostEvent
// Called by the I/O functions when input is detected
//
fun D_PostEvent(ev: event_t) {
    events[eventhead] = ev
    eventhead = (eventhead + 1) and (MAXEVENTS - 1)
}

//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
fun D_ProcessEvents() {
    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ((gamemode == commercial) && (W_CheckNumForName("map01") < 0))
        return

    while (eventtail != eventhead) {
        val ev = events[eventtail]
        if (!M_Responder(ev))  // menu ate the event otherwise
            G_Responder(ev)
        eventtail = (eventtail + 1) and (MAXEVENTS - 1)
    }
}

//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
var wipegamestate = GS_DEMOSCREEN

// C function statics of D_Display
private var viewactivestate = false
private var menuactivestate = false
private var inhelpscreensstate = false
private var fullscreen = false
private var oldgamestate = -1
private var borderdrawcount = 0

// wipe state machine (replaces the blocking do/while at the end of C D_Display)
var wipeActive = false
private var wipestart = 0

fun D_Display() {
    val y: Int
    val wipe: Boolean
    var redrawsbar: Boolean

    if (nodrawers)
        return  // for comparative timing / profiling

    redrawsbar = false

    // change the view size if needed
    if (setsizeneeded) {
        R_ExecuteSetViewSize()
        oldgamestate = -1  // force background redraw
        borderdrawcount = 3
    }

    // save the current screen if about to wipe
    if (gamestate != wipegamestate) {
        wipe = true
        wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT)
    } else
        wipe = false

    if (gamestate == GS_LEVEL && gametic != 0)
        HU_Erase()

    // do buffered drawing
    when (gamestate) {
        GS_LEVEL -> {
            if (gametic != 0) {
                if (automapactive)
                    AM_Drawer()
                if (wipe || (viewheight != 200 && fullscreen))
                    redrawsbar = true
                if (inhelpscreensstate && !inhelpscreens)
                    redrawsbar = true  // just put away the help screen
                ST_Drawer(viewheight == 200, redrawsbar)
                fullscreen = viewheight == 200
            }
        }

        GS_INTERMISSION ->
            WI_Drawer()

        GS_FINALE ->
            F_Drawer()

        GS_DEMOSCREEN ->
            D_PageDrawer()
    }

    // draw buffered stuff to screen
    I_UpdateNoBlit()

    // draw the view directly
    if (gamestate == GS_LEVEL && !automapactive && gametic != 0)
        R_RenderPlayerView(players[displayplayer])

    if (gamestate == GS_LEVEL && gametic != 0)
        HU_Drawer()

    // clean up border stuff
    if (gamestate != oldgamestate && gamestate != GS_LEVEL)
        I_SetPalette(W_CacheLumpName("PLAYPAL"))

    // see if the border needs to be initially drawn
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL) {
        viewactivestate = false  // view was not active
        R_FillBackScreen()  // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320) {
        if (menuactive || menuactivestate || !viewactivestate)
            borderdrawcount = 3
        if (borderdrawcount != 0) {
            R_DrawViewBorder()  // erase old menu stuff
            borderdrawcount--
        }
    }

    menuactivestate = menuactive
    viewactivestate = viewactive
    inhelpscreensstate = inhelpscreens
    oldgamestate = gamestate
    wipegamestate = gamestate

    // draw pause pic
    if (paused) {
        if (automapactive)
            y = 4
        else
            y = viewwindowy + 4
        V_DrawPatchDirect(viewwindowx + (scaledviewwidth - 68) / 2,
            y, 0, W_CacheLumpName("M_PAUSE"))
    }

    // menus go directly to the screen
    M_Drawer()  // menu is drawn even on top of everything
    // NetUpdate(); -- vanilla sent out any new accumulation here; the host
    // loop already calls TryRunTics/NetUpdate every frame.

    // normal update
    if (!wipe) {
        I_FinishUpdate()  // page flip or blit buffer
        return
    }

    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT)
    wipeActive = true
    wipestart = I_GetTime() - 1
}

/** One frame of the wipe (C: the do/while at the end of D_Display). */
fun D_WipeStep() {
    val nowtime = I_GetTime()
    val tics = nowtime - wipestart
    if (tics == 0)
        return
    wipestart = nowtime
    val done = wipe_ScreenWipe(wipe_Melt, 0, 0, SCREENWIDTH, SCREENHEIGHT, tics)
    I_UpdateNoBlit()
    M_Drawer()  // menu is drawn even on top of wipes
    I_FinishUpdate()  // page flip or blit buffer
    if (done)
        wipeActive = false
}

//
//  D_DoomLoop -> D_DoomStep
//  Called by the host once per display frame (vanilla looped here forever).
//  Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime, I_StartFrame, and I_StartTic
//
fun D_DoomStep() {
    if (wipeActive) {
        D_WipeStep()
        return
    }

    // frame syncronous IO operations
    I_StartFrame()

    // process one or more tics
    if (singletics) {
        I_StartTic()
        D_ProcessEvents()
        G_BuildTiccmd(netcmds[consoleplayer][maketic % BACKUPTICS])
        if (advancedemo)
            D_DoAdvanceDemo()
        M_Ticker()
        G_Ticker()
        gametic++
        maketic++
    } else {
        TryRunTics()  // will run at least one tic
    }

    S_UpdateSounds(players[consoleplayer].mo)  // move positional sounds

    // Update display, next frame, with current state.
    D_Display()
}

//
//  DEMO LOOP
//
var demosequence = 0
var pagetic = 0
var pagename = "TITLEPIC"

//
// D_PageTicker
// Handles timing for warped projection
//
fun D_PageTicker() {
    pagetic--
    if (pagetic < 0)
        D_AdvanceDemo()
}

//
// D_PageDrawer
//
fun D_PageDrawer() {
    V_DrawPatch(0, 0, 0, W_CacheLumpName(pagename))
}

//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
fun D_AdvanceDemo() {
    advancedemo = true
}

//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
fun D_DoAdvanceDemo() {
    players[consoleplayer].playerstate = PST_LIVE  // not reborn
    advancedemo = false
    usergame = false  // no save / end game here
    paused = false
    gameaction = ga_nothing

    if (gamemode == retail)
        demosequence = (demosequence + 1) % 7
    else
        demosequence = (demosequence + 1) % 6

    when (demosequence) {
        0 -> {
            if (gamemode == commercial)
                pagetic = 35 * 11
            else
                pagetic = 170
            gamestate = GS_DEMOSCREEN
            pagename = "TITLEPIC"
            if (gamemode == commercial)
                S_StartMusic(mus_dm2ttl)
            else
                S_StartMusic(mus_intro)
        }
        1 -> G_DeferedPlayDemo("demo1")
        2 -> {
            pagetic = 200
            gamestate = GS_DEMOSCREEN
            pagename = "CREDIT"
        }
        3 -> G_DeferedPlayDemo("demo2")
        4 -> {
            gamestate = GS_DEMOSCREEN
            if (gamemode == commercial) {
                pagetic = 35 * 11
                pagename = "TITLEPIC"
                S_StartMusic(mus_dm2ttl)
            } else {
                pagetic = 200

                if (gamemode == retail)
                    pagename = "CREDIT"
                else
                    pagename = "HELP2"
            }
        }
        5 -> G_DeferedPlayDemo("demo3")
        // THE DEFINITIVE DOOM Special Edition demo
        6 -> G_DeferedPlayDemo("demo4")
    }
}

//
// D_StartTitle
//
fun D_StartTitle() {
    gameaction = ga_nothing
    demosequence = -1
    D_AdvanceDemo()
}

//
// D_IdentifyVersion (C: IdentifyVersion)
// The C version checked availability of IWAD files by name; the host passes
// WAD images directly, so determine registered/commercial features by lump
// presence instead. Must be called after W_InitMultipleFiles.
//
fun D_IdentifyVersion() {
    if (W_CheckNumForName("MAP01") != -1) {
        // Commercial. (TNT/Plutonia can't be told apart without filenames.)
        gamemission = doom2
        gamemode = commercial
    } else if (W_CheckNumForName("E4M1") != -1) {
        // Retail.
        gamemission = doom
        gamemode = retail
    } else if (W_CheckNumForName("E2M1") != -1 || W_CheckNumForName("E3M1") != -1) {
        // Registered.
        gamemission = doom
        gamemode = registered
    } else if (W_CheckNumForName("E1M1") != -1) {
        // Shareware.
        gamemission = doom
        gamemode = shareware
    } else {
        println("Game mode indeterminate.")
        gamemode = indetermined
        // We don't abort. Let's see what the PWAD contains.
    }
}

//
// D_DoomMain
// Calls all startup code, parses command line options.
// The host supplies the WAD images (IWAD first, then PWADs) and the args;
// after it returns, the host drives the game by calling D_DoomStep()
// once per display frame (C: ended in the never-returning D_DoomLoop).
//
fun D_DoomMain(wads: List<ByteArray>, args: List<String>) {
    var p: Int

    myargv = listOf("doom") + args

    modifiedgame = false

    nomonsters = M_CheckParm("-nomonsters") != 0
    respawnparm = M_CheckParm("-respawn") != 0
    fastparm = M_CheckParm("-fast") != 0
    devparm = M_CheckParm("-devparm") != 0
    if (M_CheckParm("-altdeath") != 0)
        deathmatch = 2
    else if (M_CheckParm("-deathmatch") != 0)
        deathmatch = 1

    println("W_Init: Init WADfiles.")
    W_InitMultipleFiles(wads)

    D_IdentifyVersion()
    // language stays english (no doom2f.wad handling)

    val title: String
    when (gamemode) {
        retail ->
            title = "                         " +
                "The Ultimate DOOM Startup v${VERSION / 100}.${VERSION % 100}" +
                "                           "
        shareware ->
            title = "                            " +
                "DOOM Shareware Startup v${VERSION / 100}.${VERSION % 100}" +
                "                           "
        registered ->
            title = "                            " +
                "DOOM Registered Startup v${VERSION / 100}.${VERSION % 100}" +
                "                           "
        commercial ->
            title = "                         " +
                "DOOM 2: Hell on Earth v${VERSION / 100}.${VERSION % 100}" +
                "                           "
        else ->
            title = "                     " +
                "Public DOOM - v${VERSION / 100}.${VERSION % 100}" +
                "                           "
    }

    println(title)

    if (devparm)
        print(D_DEVSTR)

    // turbo option
    p = M_CheckParm("-turbo")
    if (p != 0) {
        var scale = 200

        if (p < myargc - 1)
            scale = myargv[p + 1].toIntOrNull() ?: 0
        if (scale < 10)
            scale = 10
        if (scale > 400)
            scale = 400
        println("turbo scale: $scale%")
        forwardmove[0] = forwardmove[0] * scale / 100
        forwardmove[1] = forwardmove[1] * scale / 100
        sidemove[0] = sidemove[0] * scale / 100
        sidemove[1] = sidemove[1] * scale / 100
    }

    // C added PWADs given with -file to the wad list here; the host passes
    // extra WAD images in `wads` instead -- treat those as homebrew levels.
    if (wads.size > 1)
        modifiedgame = true  // homebrew levels

    p = M_CheckParm("-playdemo")

    if (p == 0)
        p = M_CheckParm("-timedemo")

    if (p != 0 && p < myargc - 1)
        println("Playing demo ${myargv[p + 1]}.lmp.")

    // get skill / episode / map from parms
    startskill = sk_medium
    startepisode = 1
    startmap = 1
    autostart = false

    p = M_CheckParm("-skill")
    if (p != 0 && p < myargc - 1) {
        startskill = myargv[p + 1][0] - '1'
        autostart = true
    }

    p = M_CheckParm("-episode")
    if (p != 0 && p < myargc - 1) {
        startepisode = myargv[p + 1][0] - '0'
        startmap = 1
        autostart = true
    }

    p = M_CheckParm("-timer")
    if (p != 0 && p < myargc - 1 && deathmatch != 0) {
        val time = myargv[p + 1].toIntOrNull() ?: 0
        print("Levels will end after $time minute")
        if (time > 1)
            print("s")
        println(".")
    }

    p = M_CheckParm("-avg")
    if (p != 0 && p < myargc - 1 && deathmatch != 0)
        println("Austin Virtual Gaming: Levels will end after 20 minutes")

    p = M_CheckParm("-warp")
    if (p != 0 && p < myargc - 1) {
        if (gamemode == commercial)
            startmap = myargv[p + 1].toIntOrNull() ?: 0
        else {
            startepisode = myargv[p + 1][0] - '0'
            startmap = myargv[p + 2][0] - '0'
        }
        autostart = true
    }

    // Check for -file in shareware
    if (modifiedgame) {
        // These are the lumps that will be checked in IWAD,
        // if any one is not present, execution will be aborted.
        val name = arrayOf(
            "e2m1", "e2m2", "e2m3", "e2m4", "e2m5", "e2m6", "e2m7", "e2m8", "e2m9",
            "e3m1", "e3m3", "e3m3", "e3m4", "e3m5", "e3m6", "e3m7", "e3m8", "e3m9",
            "dphoof", "bfgga0", "heada1", "cybra1", "spida1d1"
        )

        if (gamemode == shareware)
            I_Error("\nYou cannot -file with the shareware version. Register!")

        // Check for fake IWAD with right name,
        // but w/o all the lumps of the registered version.
        if (gamemode == registered)
            for (i in 0 until 23)
                if (W_CheckNumForName(name[i]) < 0)
                    I_Error("\nThis is not the registered version.")
    }

    // Iff additonal PWAD files are used, print modified banner
    if (modifiedgame) {
        println(
            "===========================================================================\n" +
            "ATTENTION:  This version of DOOM has been modified.  If you would like to\n" +
            "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n" +
            "        You will not receive technical support for modified games.\n" +
            "                      press enter to continue\n" +
            "==========================================================================="
        )
    }

    // Check and print which version is executed.
    when (gamemode) {
        shareware, indetermined ->
            println(
                "===========================================================================\n" +
                "                                Shareware!\n" +
                "==========================================================================="
            )
        registered, retail, commercial ->
            println(
                "===========================================================================\n" +
                "                 Commercial product - do not distribute!\n" +
                "         Please report software piracy to the SPA: 1-800-388-PIR8\n" +
                "==========================================================================="
            )
        else -> {
            // Ouch.
        }
    }

    println("V_Init: allocate screens.")
    V_Init()

    println("M_LoadDefaults: Load system defaults.")
    M_LoadDefaults()  // load before initing other systems

    println("M_Init: Init miscellaneous info.")
    M_Init()

    print("R_Init: Init DOOM refresh daemon - ")
    R_Init()

    // Register A_* codepointers and resolve state action names
    // (replaces C info.c's static action-function table).
    P_RegisterEnemyActions()
    P_RegisterPsprActions()
    InfoResolveActions()

    println("\nP_Init: Init Playloop state.")
    P_Init()

    println("I_Init: Setting up machine state.")
    I_InitGraphics()

    println("D_CheckNetGame: Checking network game status.")
    // D_CheckNetGame: networking not ported -- single local player.
    netgame = false
    consoleplayer = 0
    displayplayer = 0
    playeringame[0] = true
    ticdup = 1

    println("startskill $startskill  deathmatch: $deathmatch  startmap: $startmap  startepisode: $startepisode")

    println("S_Init: Setting up sound.")
    S_Init(snd_SfxVolume /* *8 */, snd_MusicVolume /* *8 */)

    println("HU_Init: Setting up heads up display.")
    HU_Init()

    println("ST_Init: Init status bar.")
    ST_Init()

    // start the apropriate game based on parms
    p = M_CheckParm("-record")

    if (p != 0 && p < myargc - 1) {
        G_RecordDemo(myargv[p + 1])
        autostart = true
    }

    p = M_CheckParm("-playdemo")
    if (p != 0 && p < myargc - 1) {
        singledemo = true  // quit after one demo
        G_DeferedPlayDemo(myargv[p + 1])
        if (demorecording)
            G_BeginRecording()  // C: top of D_DoomLoop
        return  // C: D_DoomLoop() -- host drives D_DoomStep() from here on
    }

    p = M_CheckParm("-timedemo")
    if (p != 0 && p < myargc - 1) {
        G_TimeDemo(myargv[p + 1])
        if (demorecording)
            G_BeginRecording()  // C: top of D_DoomLoop
        return  // C: D_DoomLoop() -- host drives D_DoomStep() from here on
    }

    p = M_CheckParm("-loadgame")
    if (p != 0 && p < myargc - 1) {
        G_LoadGame("$SAVEGAMENAME${myargv[p + 1][0]}.dsg")
    }

    if (gameaction != ga_loadgame) {
        if (autostart || netgame)
            G_InitNew(startskill, startepisode, startmap)
        else
            D_StartTitle()  // start up intro loop
    }

    if (demorecording)
        G_BeginRecording()  // C: top of D_DoomLoop

    // C: D_DoomLoop() -- never returns; here the host drives D_DoomStep().
}
