
package doom.engine.audio

internal class SoundDefinitionState {
    val sSfx: Array<SoundEffectDefinition> by lazy(LazyThreadSafetyMode.NONE) { arrayOf(
        SoundEffectDefinition("none", false, 0, -1, -1, -1),
        SoundEffectDefinition("pistol", false, 64, -1, -1, -1),
        SoundEffectDefinition("shotgn", false, 64, -1, -1, -1),
        SoundEffectDefinition("sgcock", false, 64, -1, -1, -1),
        SoundEffectDefinition("dshtgn", false, 64, -1, -1, -1),
        SoundEffectDefinition("dbopn", false, 64, -1, -1, -1),
        SoundEffectDefinition("dbcls", false, 64, -1, -1, -1),
        SoundEffectDefinition("dbload", false, 64, -1, -1, -1),
        SoundEffectDefinition("plasma", false, 64, -1, -1, -1),
        SoundEffectDefinition("bfg", false, 64, -1, -1, -1),
        SoundEffectDefinition("sawup", false, 64, -1, -1, -1),
        SoundEffectDefinition("sawidl", false, 118, -1, -1, -1),
        SoundEffectDefinition("sawful", false, 64, -1, -1, -1),
        SoundEffectDefinition("sawhit", false, 64, -1, -1, -1),
        SoundEffectDefinition("rlaunc", false, 64, -1, -1, -1),
        SoundEffectDefinition("rxplod", false, 70, -1, -1, -1),
        SoundEffectDefinition("firsht", false, 70, -1, -1, -1),
        SoundEffectDefinition("firxpl", false, 70, -1, -1, -1),
        SoundEffectDefinition("pstart", false, 100, -1, -1, -1),
        SoundEffectDefinition("pstop", false, 100, -1, -1, -1),
        SoundEffectDefinition("doropn", false, 100, -1, -1, -1),
        SoundEffectDefinition("dorcls", false, 100, -1, -1, -1),
        SoundEffectDefinition("stnmov", false, 119, -1, -1, -1),
        SoundEffectDefinition("swtchn", false, 78, -1, -1, -1),
        SoundEffectDefinition("swtchx", false, 78, -1, -1, -1),
        SoundEffectDefinition("plpain", false, 96, -1, -1, -1),
        SoundEffectDefinition("dmpain", false, 96, -1, -1, -1),
        SoundEffectDefinition("popain", false, 96, -1, -1, -1),
        SoundEffectDefinition("vipain", false, 96, -1, -1, -1),
        SoundEffectDefinition("mnpain", false, 96, -1, -1, -1),
        SoundEffectDefinition("pepain", false, 96, -1, -1, -1),
        SoundEffectDefinition("slop", false, 78, -1, -1, -1),
        SoundEffectDefinition("itemup", true, 78, -1, -1, -1),
        SoundEffectDefinition("wpnup", true, 78, -1, -1, -1),
        SoundEffectDefinition("oof", false, 96, -1, -1, -1),
        SoundEffectDefinition("telept", false, 32, -1, -1, -1),
        SoundEffectDefinition("posit1", true, 98, -1, -1, -1),
        SoundEffectDefinition("posit2", true, 98, -1, -1, -1),
        SoundEffectDefinition("posit3", true, 98, -1, -1, -1),
        SoundEffectDefinition("bgsit1", true, 98, -1, -1, -1),
        SoundEffectDefinition("bgsit2", true, 98, -1, -1, -1),
        SoundEffectDefinition("sgtsit", true, 98, -1, -1, -1),
        SoundEffectDefinition("cacsit", true, 98, -1, -1, -1),
        SoundEffectDefinition("brssit", true, 94, -1, -1, -1),
        SoundEffectDefinition("cybsit", true, 92, -1, -1, -1),
        SoundEffectDefinition("spisit", true, 90, -1, -1, -1),
        SoundEffectDefinition("bspsit", true, 90, -1, -1, -1),
        SoundEffectDefinition("kntsit", true, 90, -1, -1, -1),
        SoundEffectDefinition("vilsit", true, 90, -1, -1, -1),
        SoundEffectDefinition("mansit", true, 90, -1, -1, -1),
        SoundEffectDefinition("pesit", true, 90, -1, -1, -1),
        SoundEffectDefinition("sklatk", false, 70, -1, -1, -1),
        SoundEffectDefinition("sgtatk", false, 70, -1, -1, -1),
        SoundEffectDefinition("skepch", false, 70, -1, -1, -1),
        SoundEffectDefinition("vilatk", false, 70, -1, -1, -1),
        SoundEffectDefinition("claw", false, 70, -1, -1, -1),
        SoundEffectDefinition("skeswg", false, 70, -1, -1, -1),
        SoundEffectDefinition("pldeth", false, 32, -1, -1, -1),
        SoundEffectDefinition("pdiehi", false, 32, -1, -1, -1),
        SoundEffectDefinition("podth1", false, 70, -1, -1, -1),
        SoundEffectDefinition("podth2", false, 70, -1, -1, -1),
        SoundEffectDefinition("podth3", false, 70, -1, -1, -1),
        SoundEffectDefinition("bgdth1", false, 70, -1, -1, -1),
        SoundEffectDefinition("bgdth2", false, 70, -1, -1, -1),
        SoundEffectDefinition("sgtdth", false, 70, -1, -1, -1),
        SoundEffectDefinition("cacdth", false, 70, -1, -1, -1),
        SoundEffectDefinition("skldth", false, 70, -1, -1, -1),
        SoundEffectDefinition("brsdth", false, 32, -1, -1, -1),
        SoundEffectDefinition("cybdth", false, 32, -1, -1, -1),
        SoundEffectDefinition("spidth", false, 32, -1, -1, -1),
        SoundEffectDefinition("bspdth", false, 32, -1, -1, -1),
        SoundEffectDefinition("vildth", false, 32, -1, -1, -1),
        SoundEffectDefinition("kntdth", false, 32, -1, -1, -1),
        SoundEffectDefinition("pedth", false, 32, -1, -1, -1),
        SoundEffectDefinition("skedth", false, 32, -1, -1, -1),
        SoundEffectDefinition("posact", true, 120, -1, -1, -1),
        SoundEffectDefinition("bgact", true, 120, -1, -1, -1),
        SoundEffectDefinition("dmact", true, 120, -1, -1, -1),
        SoundEffectDefinition("bspact", true, 100, -1, -1, -1),
        SoundEffectDefinition("bspwlk", true, 100, -1, -1, -1),
        SoundEffectDefinition("vilact", true, 100, -1, -1, -1),
        SoundEffectDefinition("noway", false, 78, -1, -1, -1),
        SoundEffectDefinition("barexp", false, 60, -1, -1, -1),
        SoundEffectDefinition("punch", false, 64, -1, -1, -1),
        SoundEffectDefinition("hoof", false, 70, -1, -1, -1),
        SoundEffectDefinition("metal", false, 70, -1, -1, -1),
        SoundEffectDefinition("chgun", false, 64, SFX_PISTOL, 150, 0),
        SoundEffectDefinition("tink", false, 60, -1, -1, -1),
        SoundEffectDefinition("bdopn", false, 100, -1, -1, -1),
        SoundEffectDefinition("bdcls", false, 100, -1, -1, -1),
        SoundEffectDefinition("itmbk", false, 100, -1, -1, -1),
        SoundEffectDefinition("flame", false, 32, -1, -1, -1),
        SoundEffectDefinition("flamst", false, 32, -1, -1, -1),
        SoundEffectDefinition("getpow", false, 60, -1, -1, -1),
        SoundEffectDefinition("bospit", false, 70, -1, -1, -1),
        SoundEffectDefinition("boscub", false, 70, -1, -1, -1),
        SoundEffectDefinition("bossit", false, 70, -1, -1, -1),
        SoundEffectDefinition("bospn", false, 70, -1, -1, -1),
        SoundEffectDefinition("bosdth", false, 70, -1, -1, -1),
        SoundEffectDefinition("manatk", false, 70, -1, -1, -1),
        SoundEffectDefinition("mandth", false, 70, -1, -1, -1),
        SoundEffectDefinition("sssit", false, 70, -1, -1, -1),
        SoundEffectDefinition("ssdth", false, 70, -1, -1, -1),
        SoundEffectDefinition("keenpn", false, 70, -1, -1, -1),
        SoundEffectDefinition("keendt", false, 70, -1, -1, -1),
        SoundEffectDefinition("skeact", false, 70, -1, -1, -1),
        SoundEffectDefinition("skesit", false, 70, -1, -1, -1),
        SoundEffectDefinition("skeatk", false, 70, -1, -1, -1),
        SoundEffectDefinition("radio", false, 60, -1, -1, -1),
    ) }

    val sMusic: Array<MusicTrack> by lazy(LazyThreadSafetyMode.NONE) { arrayOf(
        MusicTrack(""),
        MusicTrack("e1m1"),
        MusicTrack("e1m2"),
        MusicTrack("e1m3"),
        MusicTrack("e1m4"),
        MusicTrack("e1m5"),
        MusicTrack("e1m6"),
        MusicTrack("e1m7"),
        MusicTrack("e1m8"),
        MusicTrack("e1m9"),
        MusicTrack("e2m1"),
        MusicTrack("e2m2"),
        MusicTrack("e2m3"),
        MusicTrack("e2m4"),
        MusicTrack("e2m5"),
        MusicTrack("e2m6"),
        MusicTrack("e2m7"),
        MusicTrack("e2m8"),
        MusicTrack("e2m9"),
        MusicTrack("e3m1"),
        MusicTrack("e3m2"),
        MusicTrack("e3m3"),
        MusicTrack("e3m4"),
        MusicTrack("e3m5"),
        MusicTrack("e3m6"),
        MusicTrack("e3m7"),
        MusicTrack("e3m8"),
        MusicTrack("e3m9"),
        MusicTrack("inter"),
        MusicTrack("intro"),
        MusicTrack("bunny"),
        MusicTrack("victor"),
        MusicTrack("introa"),
        MusicTrack("runnin"),
        MusicTrack("stalks"),
        MusicTrack("countd"),
        MusicTrack("betwee"),
        MusicTrack("doom"),
        MusicTrack("the_da"),
        MusicTrack("shawn"),
        MusicTrack("ddtblu"),
        MusicTrack("in_cit"),
        MusicTrack("dead"),
        MusicTrack("stlks2"),
        MusicTrack("theda2"),
        MusicTrack("doom2"),
        MusicTrack("ddtbl2"),
        MusicTrack("runni2"),
        MusicTrack("dead2"),
        MusicTrack("stlks3"),
        MusicTrack("romero"),
        MusicTrack("shawn2"),
        MusicTrack("messag"),
        MusicTrack("count2"),
        MusicTrack("ddtbl3"),
        MusicTrack("ampie"),
        MusicTrack("theda3"),
        MusicTrack("adrian"),
        MusicTrack("messg2"),
        MusicTrack("romer2"),
        MusicTrack("tense"),
        MusicTrack("shawn3"),
        MusicTrack("openin"),
        MusicTrack("evil"),
        MusicTrack("ultima"),
        MusicTrack("read_m"),
        MusicTrack("dm2ttl"),
        MusicTrack("dm2int"),
    ) }
}
